### ISSUE TITLE
Features: timestamp and server listening log

### ISSUE THREAD

**Issue by Xu-pixel** [tanishqmanuja/nice-logger#1]
Thank you for your awesome works very much, Would you happen to have the time and capacity to add timestamps and server startup identifiers? like logixlysia do. I would greatly appreciate it

![image](https://github.com/user-attachments/assets/24dbaf47-4d3e-49b8-8f3c-ca90f092f39a)

**Comment by tanishqmanuja** [comment]
Sure, would look something like this. (ref: 7cfede2279d3f9fa0bce3e565fe95bb256f5e179)
![image](https://github.com/user-attachments/assets/9f45ffbb-cee4-47bd-9d73-05c6b5a2d8e9)

Starting from v1.0.2 you can configure to print timestamp or banner like this
```ts
const app = new Elysia()
  .use(
    logger({
      mode: "live",
      withBanner: true,
      withTimestamp: true,
    }),
  )
  .listen(3000)
```

**Comment by Xu-pixel** [comment]
wow！You are a generous and highly efficient programmer.Thank you very much！I think this is the most suitable elysia logger for me now.
