### ISSUE TITLE
Add Custom Timestamp Function Support

### ISSUE THREAD

**Issue by henilmalaviya** [tanishqmanuja/nice-logger#2]
Hey, first of all, great work on this project! I have been using this logger in one of my projects, and it’s been really helpful.

I noticed the existing `withTimestamp` boolean (from #1) but typically, I prefer using ISO timestamps for logging across all of my projects. While looking at the code, I came across this part:

https://github.com/tanishqmanuja/nice-logger/blob/b797aec038018d1a05705ac0ae1e794ea8d73eb4/src/index.ts#L55-L58

i was thinking to add something (like `getTimestamp` function in `LoggerOptions`) so that i can pass my custom function that returns a string.

**Comment by henilmalaviya** [comment]
I also noticed a similar pattern in `withBanner` option, i think you can also do similar thing with `withTimestamp` option. if its a function call it (or capture the return and console it instead).

```ts
logger({
    mode: 'live',
    withTimestamp: ()=>{
        return new Date().toISOString();
    }
})
```

**Comment by tanishqmanuja** [comment]
Thanks, added in v1.0.6
