### ISSUE TITLE
Chaining .use(logger()) breaks Eden type resolution

### ISSUE THREAD

**Issue by dy0gu** [tanishqmanuja/nice-logger#4]
# Minimal reproduction

## With logger:

```typescript
import { Elysia } from "elysia"
import { logger } from "@tqman/nice-logger";

const app = new Elysia()
    .use(logger())
    .listen(
        3000,
        (server) => {
            console.log(server.url.origin);
        },
    );

export type App = typeof app
```
![{A5FC346C-9B6E-4F24-8E9F-5F83F48965A2}](https://github.com/user-attachments/assets/4c9d2adc-65a7-4fc0-93aa-560d86310ea7)

## Without logger:

```typescript
import { Elysia } from "elysia"

const app = new Elysia()
    .listen(
        3000,
        (server) => {
            console.log(server.url.origin);
        },
    );

export type App = typeof app
```

![{E40BC823-23E0-4A7B-89A2-627D247DBC6B}](https://github.com/user-attachments/assets/5df7b978-722a-4648-8607-9a40543c2408)

# Notes

As you can see, chaining the logger into the app definition breaks the Elysia type definition as it automatically becomes `any`.

For the purposes of this reproduction I didn't add any routes but the point is that removing the logger brings back the correct typing.

**Comment by tanishqmanuja** [comment]
Can you test any official elysia plugin such as elysia/html etc etc and check if the types are fine?

This would help me replicate the same code pattern if they work with correct typings

**Comment by dy0gu** [comment]
Sure, I can confirm all the official Elysia plugins are preserving the types correctly.

As for community ones, I switched to [elysia-logger](https://github.com/bogeychan/elysia-logger) in the meantime and the types are also working with it.

**Comment by tanishqmanuja** [comment]
Thanks for reporting the issue 💯

Can you confirm if the new version works ? Just updated the build system to match what official elysia plugins use i.e. a combination of both `TSUP` and `TSC` to generate the types correctly.

**Comment by dy0gu** [comment]
Yep, seems fixed to me, closing this!
